// 髪型バリエーション 8x8 マトリクス
// 顔中央 (col 2-5 / row 2-4) は基本 null にして肌が見えるようにし、サイドと頭上だけに髪を置く
import type { HairId, PixelMatrix } from '@/types'

const _: null = null

export const HAIR_MATRICES: Record<HairId, PixelMatrix> = {
  short: [
    [_, _, 'hair', 'hair', 'hair', 'hair', _, _],
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  long: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  bald: [
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  mohawk: [
    [_, _, _, 'hair', 'hair', _, _, _],
    [_, _, _, 'hair', 'hair', _, _, _],
    [_, _, _, 'hair', 'hair', _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  topknot: [
    [_, _, _, 'hair', 'hair', _, _, _],
    [_, _, 'hair', 'hair', 'hair', 'hair', _, _],
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // 風ヘア — 片側へ流した前髪と軽い跳ね感で動きを出す
  windSweep: [
    [_, _, 'hair', 'hair', 'hair', 'hair', 'hair', _],
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', 'hair', _, _, _, 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // 餓狼ヘア — 逆立つ前髪と横に張る毛先で格闘ゲーム風の勢いを出す
  garou: [
    [_, _, 'hair', _, 'hair', _, _, _],
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', _, _],
    ['hair', 'hair', 'hair', _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  curl: [
    [_, 'hair', 'hair', _, _, 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ナチュラルショートボブ — コンパクトなクラウン + 2px サイド + あご先テーパー
  neatBob: [
    [_, _, 'hair', 'hair', 'hair', 'hair', _, _],
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ソフトボブ — 丸みのある前髪と内巻きの毛先で柔らかく見せる定番ボブ
  softBob: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', 'hair', _, _, 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', 'hair', _, _, 'hair', 'hair', _],
    [_, _, 'hair', 'hair', 'hair', 'hair', _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // 日本のおかっぱ (ボブ) — 一直線の前髪 + 顎ラインまでの横髪
  bob: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ポニーテール — 頭頂をしっかり覆い、右側に縦のしっぽを垂らす
  ponytail: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', _, _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', 'hair'],
    [_, _, _, _, _, _, _, 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ツインテール — 頭頂を覆い、両サイドに下ろした二房
  twintail: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', _, _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', _, _, _, _, _, _, 'hair'],
    ['hair', _, _, _, _, _, _, 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ロングウェーブ — ボリュームのある肩までの巻き髪
  wavy: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', _, _, _, _, _, _, 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
  ],
  // 姫カット — 一直線の前髪 + ストレートで長いサイドヘア
  hime: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // うさ耳フード — 左右に尖った耳 + 顔を包むフード (特定キャラを避けた汎用シルエット)
  hood: [
    [_, 'hair', _, _, _, _, 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ぱっつん前髪ボブ — 一直線の前髪で額を覆い、顎ラインで切り揃えた東アジア女性の定番
  bobBangs: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // 前髪ありウェーブ — 前髪 + 外側に波打つパーマシルエット
  wavyBangs: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', _, _, _, _, _, _, 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    ['hair', _, _, _, _, _, _, 'hair'],
  ],
  // センター分けロング — 真ん中分けで肩下まで伸びるストレートロング
  longStraight: [
    [_, 'hair', 'hair', _, _, 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
  ],
  // Cカールミディアム — 毛先が内側に巻き込むパーマボブ
  cCurlBob: [
    [_, 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', _],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, 'hair', 'hair', 'hair', 'hair', _, _],
    [_, _, _, _, _, _, _, _],
  ],
  // ヒドル専用帽子 — 左右の耳とフード縁を強め、クロミらしい外周シルエットを優先する
  kuroxxx: [
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    ['hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair', 'hair'],
    ['hair', 'hair', _, _, _, _, 'hair', 'hair'],
    [_, 'hair', _, _, _, _, 'hair', _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
    [_, _, _, _, _, _, _, _],
  ],
}
